# This example demonstrates the ability to pass artifacts
# from one step to the next.
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-passing-
spec:
  entrypoint: artifact-example
  templates:
  - name: artifact-example
    steps:
    - - name: generate-artifact
        template: hello-world-to-file
    - - name: consume-artifact
        template: print-message-from-file
        arguments:
          artifacts:
          - name: foo
            from: "{{steps.generate-artifact.outputs.artifacts.file-foo}}"
          - name: bar
            from: "{{steps.generate-artifact.outputs.artifacts.file-bar}}"

  - name: hello-world-to-file
    container:
      image: busybox
      command: [sh, -c]
      args: ["sleep 1; dd if=/dev/zero of=/tmp/hello_world bs=1024000 count=5120"]
    outputs:
      artifacts:
      - name: file-foo
        path: /tmp/hello_world.txt
      - name: file-bar
        path: /tmp/hello_world.txt

  - name: print-message-from-file
    inputs:
      artifacts:
      - name: foo
        path: /tmp/message
      - name: bar
        path: /tmp/message2
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["cat /tmp/message"]
