apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: sleep-when
  labels:
    workflows.argoproj.io/do-not-test: "true" # CronWorkflow
spec:
  schedule: "* * * * *"
  concurrencyPolicy: "Allow"
  when: "{{= cronworkflow.lastScheduledTime == nil || (now() - cronworkflow.lastScheduledTime).Seconds() > 360 }}"
  workflowSpec:
    entrypoint: sleep-busybox
    templates:
      - name: sleep-busybox
        container:
          image: busybox
          command: [sleep]
          args: ["10"]
