# run forever
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: forever
  labels:
    workflows.argoproj.io/do-not-test: "true" # Takes 1000 seconds
spec:
  entrypoint: main
  templates:
    - name: main
      container:
        image: busybox
        command: [sh, "-c", "for I in $(seq 1 1000) ; do echo $I ; sleep 1s; done"]
